# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.14.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.14.0'
    - run: npm ci
    - run: npm run build
    - run: npm t
    - run: npm run e2e
